#!/usr/bin/python
#find * | grep "/"|awk '{printf "mv "$0; gsub("pechip", "zephyr", $0);print " "$0;}'|sh
import os

def inplace_change(filename, old_string, new_string):
    s=open(filename).read()
    if old_string in s:
        print 'Changing "{old_string}" to "{new_string}"'.format(**locals())
        s=s.replace(old_string, new_string)
        f=open(filename, 'w')
        f.write(s)
        f.flush()
        f.close()
    else:
        print 'No occurances of "{old_string}" found.'.format(**locals())

def replace_file(filename):
    print (filename)
    #inplace_change(filename, "cos/public_cos.h", "public_cos.h")
    #inplace_change(filename, "applications/packet-io/mexpr_pkt_public.h", "mexpr_pkt_public.h")
    #inplace_change(filename, "applications/packet-io/mexpr_pkt_ring_public.h", "mexpr_pkt_ring_public.h")
    #inplace_change(filename, "toolkits/jencap/jmexpr_encap_public.h", "jmexpr_encap_public.h")
    #inplace_change(filename, "toolkits/jencap/jmexpr_encap_tmplt_public.h", "jmexpr_encap_tmplt_public.h")
    #inplace_change(filename, "toolkits/jencap/jmexpr_encap_desc_public.h", "jmexpr_encap_desc_public.h")
    #inplace_change(filename, "toolkits/jfdb/jmexpr_fdb_public.h", "jmexpr_fdb_public.h")
    #inplace_change(filename, "toolkits/jnh/jmexpr_nh_adaptive_public.h", "jmexpr_nh_adaptive_public.h")
    #inplace_change(filename, "toolkits/jnh/jmexpr_nh_public.h", "jmexpr_nh_public.h")
    #inplace_change(filename, "toolkits/jutils/jmexpr_slu_hash_public.h", "jmexpr_slu_hash_public.h")
    #inplace_change(filename, "toolkits/jchash/jmexpr_slu_hash_public.h", "jmexpr_slu_hash_public.h")
    #inplace_change(filename, "jnh/jmexpr_nh_public.h", "jmexpr_nh_public.h")
    #inplace_change(filename, "jencap/jmexpr_encap_public.h", "jmexpr_encap_public.h")
    #inplace_change(filename, "jencap/jmexpr_encap_tmplt_public.h", "jmexpr_encap_tmplt_public.h")
    #inplace_change(filename, "jencap/jmexpr_encap_desc_public.h", "jmexpr_encap_desc_public.h")
    #inplace_change(filename, "toolkits/jnh/jmexpr_nh_mem.h", "jmexpr_nh_mem.h")
    #inplace_change(filename, "jnh/jmexpr_nh_mem.h", "jmexpr_nh_mem.h")
    #inplace_change(filename, "packet-io/mexpr_pkt_public.h", "mexpr_pkt_public.h")
    #inplace_change(filename, "packet-io/mexpr_pkt_ring_public.h", "mexpr_pkt_ring_public.h")
    inplace_change(filename, "", "")
    inplace_change(filename,"if_esi.h","priv_if_esi.h")
    inplace_change(filename,"if_mymac_mexpr.h","priv_if_mymac_mexpr.h")
    inplace_change(filename,"if_mtip_mexpr.h","priv_if_mtip_mexpr.h")
    inplace_change(filename,"if_packet_qfx.h","priv_if_packet_qfx.h")
    inplace_change(filename,"if_vrrpmac_mexpr.h","priv_if_vrrpmac_mexpr.h")
    inplace_change(filename,"if_port_mexpr.h","priv_if_port_mexpr.h")
    inplace_change(filename,"if_cfm.h","priv_if_cfm.h")
    inplace_change(filename,"if_dot1br_qfx.h","priv_if_dot1br_qfx.h")
    inplace_change(filename,"if_tree_qfx.h","priv_if_tree_qfx.h")
    inplace_change(filename,"if_vlan_qfx.h","priv_if_vlan_qfx.h")
    inplace_change(filename,"if_mexpr_cr.h","priv_if_mexpr_cr.h")
    inplace_change(filename,"if_cfm_mexpr.h","priv_if_cfm_mexpr.h")
    inplace_change(filename,"if_shared_qfx.h","priv_if_shared_qfx.h")
    inplace_change(filename,"if_l2_qfx.h","priv_if_l2_qfx.h")
    inplace_change(filename,"if_incl_qfx.h","priv_if_incl_qfx.h")
    inplace_change(filename,"rt_tree.h","priv_rt_tree.h")
    inplace_change(filename,"dfw_tree.h","priv_dfw_tree.h")
    inplace_change(filename,"dfw_asic_sfm.h","priv_dfw_asic_sfm.h")
    inplace_change(filename,"dfw_asic_alpha.h","priv_dfw_asic_alpha.h")
    inplace_change(filename,"dfw_asic_sfm_mexpr.h","priv_dfw_asic_sfm_mexpr.h")
    inplace_change(filename,"dfw_asic_plct.h","priv_dfw_asic_plct.h")
    inplace_change(filename,"dfw_base_inst.h","priv_dfw_base_inst.h")
    inplace_change(filename,"dfw_pfe_inst.h","priv_dfw_pfe_inst.h")
    inplace_change(filename,"dfw_hw_inst.h","priv_dfw_hw_inst.h")
    inplace_change(filename,"dfw_asic_action.h","priv_dfw_asic_action.h")
    inplace_change(filename,"dfw_inst.h","priv_dfw_inst.h")
    inplace_change(filename,"dfw_asic.h","priv_dfw_asic.h")
    inplace_change(filename,"flt_compiler.h","priv_flt_compiler.h")
    inplace_change(filename,"dfw_entry.h","priv_dfw_entry.h")
    inplace_change(filename,"dfw_plct.h","priv_dfw_plct.h")
    inplace_change(filename,"dfw_term.h","priv_dfw_term.h")
    inplace_change(filename,"dfw_action.h","priv_dfw_action.h")
    inplace_change(filename,"dfw_unit_test.h","priv_dfw_unit_test.h")
    inplace_change(filename,"dfw_topo.h","priv_dfw_topo.h")
    inplace_change(filename,"dfw_bind_point.h","priv_dfw_bind_point.h")
    inplace_change(filename,"dfw_sfm.h","priv_dfw_sfm.h")
    inplace_change(filename,"dfw_match.h","priv_dfw_match.h")
    inplace_change(filename,"dfw_extra_terms.h","priv_dfw_extra_terms.h")
    inplace_change(filename,"dfw_topo_item.h","priv_dfw_topo_item.h")
    inplace_change(filename,"dfw_shim.h","priv_dfw_shim.h")
    inplace_change(filename,"plct_tree.h","priv_plct_tree.h")
    inplace_change(filename,"cos_utils.h","priv_cos_utils.h")
    inplace_change(filename,"cos_mexpr_tree.h","priv_cos_mexpr_tree.h")
    inplace_change(filename,"cos_fc_to_q_map.h","priv_cos_fc_to_q_map.h")
    inplace_change(filename,"log2_func.h","priv_log2_func.h")
    inplace_change(filename,"cos_drop_profile.h","priv_cos_drop_profile.h")
    inplace_change(filename,"cos_fabric.h","priv_cos_fabric.h")
    inplace_change(filename,"cos_sched.h","priv_cos_sched.h")
    inplace_change(filename,"cos_internal_apis.h","priv_cos_internal_apis.h")
    inplace_change(filename,"cos_drop_profile_mexpr.h","priv_cos_drop_profile_mexpr.h")
    inplace_change(filename,"cos_internal_apis_mexpr.h","priv_cos_internal_apis_mexpr.h")
    inplace_change(filename,"cos_adf_apis.h","priv_cos_adf_apis.h")
    inplace_change(filename,"cos_componentized.h","priv_cos_componentized.h")
    inplace_change(filename,"cos_rate_wheel.h","priv_cos_rate_wheel.h")
    inplace_change(filename,"cos_cmf_apis.h","priv_cos_cmf_apis.h")
    inplace_change(filename,"cos_rewrite.h","priv_cos_rewrite.h")
    inplace_change(filename,"cos_classifier.h","priv_cos_classifier.h")
    inplace_change(filename,"cos_common_defines.h","priv_cos_common_defines.h")
    inplace_change(filename,"cos_pgq.h","priv_cos_pgq.h")
    inplace_change(filename,"analyzer_parser.h","priv_analyzer_parser.h")
    inplace_change(filename,"analyzer_tree.h","priv_analyzer_tree.h")
    inplace_change(filename,"analyzer_incl.h","priv_analyzer_incl.h")
    inplace_change(filename,"caem_capability_mexpress.h","priv_caem_capability_mexpress.h")
    inplace_change(filename,"caem_toe.h","priv_caem_toe.h")
    inplace_change(filename,"caem_halp_mexpr.h","priv_caem_halp_mexpr.h")
    inplace_change(filename,"nh_host_mexpr_qfx.h","priv_nh_host_mexpr_qfx.h")
    inplace_change(filename,"nh_encaps.h","priv_nh_encaps.h")
    inplace_change(filename,"nh_mexpr_tree.h","priv_nh_mexpr_tree.h")
    inplace_change(filename,"nh_virtual.h","priv_nh_virtual.h")
    inplace_change(filename,"nh_ifl_list_mexpr_cr.h","priv_nh_ifl_list_mexpr_cr.h")
    inplace_change(filename,"nh_host.h","priv_nh_host.h")
    inplace_change(filename,"nh_composite_lb.h","priv_nh_composite_lb.h")
    inplace_change(filename,"nh_host_anchor_qfx.h","priv_nh_host_anchor_qfx.h")
    inplace_change(filename,"nh_host_mexpr_qfx_q.h","priv_nh_host_mexpr_qfx_q.h")
    inplace_change(filename,"nh_unilist.h","priv_nh_unilist.h")
    inplace_change(filename,"sflow_halp.h","priv_sflow_halp.h")
    inplace_change(filename,"mexpr_sflow_tree.h","priv_mexpr_sflow_tree.h")
    inplace_change(filename,"sflow_tree.h","priv_sflow_tree.h")
    inplace_change(filename,"mexpr_pkt_dbg.h","priv_mexpr_pkt_dbg.h")
    inplace_change(filename,"mexpr_pkt_ring.h","priv_mexpr_pkt_ring.h")
    inplace_change(filename,"mexpr_pkt_tree.h","priv_mexpr_pkt_tree.h")
    inplace_change(filename,"mexpr_pkt_dma.h","priv_mexpr_pkt_dma.h")
    inplace_change(filename,"mexpr_pkt_xfer_toe.h","priv_mexpr_pkt_xfer_toe.h")
    inplace_change(filename,"mexpr_pkt_ddos_shared.h","priv_mexpr_pkt_ddos_shared.h")
    inplace_change(filename,"mexpr_pkt_queue.h","priv_mexpr_pkt_queue.h")
    inplace_change(filename,"mexpr_pkt_incl.h","priv_mexpr_pkt_incl.h")
    inplace_change(filename,"mexpr_pkt_inline_ka.h","priv_mexpr_pkt_inline_ka.h")
    inplace_change(filename,"mexpr_pkt_ddos.h","priv_mexpr_pkt_ddos.h")
    inplace_change(filename,"l2_scntl.h","priv_l2_scntl.h")
    inplace_change(filename,"l2_rt.h","priv_l2_rt.h")
    inplace_change(filename,"l2_incl.h","priv_l2_incl.h")
    inplace_change(filename,"l2_learning.h","priv_l2_learning.h")
    inplace_change(filename,"l2_sa.h","priv_l2_sa.h")
    inplace_change(filename,"l2_flex_vlan.h","priv_l2_flex_vlan.h")
    inplace_change(filename,"l2_aging.h","priv_l2_aging.h")
    inplace_change(filename,"l2_bd.h","priv_l2_bd.h")
    inplace_change(filename,"l2_fdb.h","priv_l2_fdb.h")
    inplace_change(filename,"l2_tree.h","priv_l2_tree.h")
    inplace_change(filename,"jmexpr_scv.h","priv_jmexpr_scv.h")
    inplace_change(filename,"jmexpr_fcv_tree.h","priv_jmexpr_fcv_tree.h")
    inplace_change(filename,"jmexpr_fcv_entry.h","priv_jmexpr_fcv_entry.h")
    inplace_change(filename,"jmexpr_fcv_asic_pe.h","priv_jmexpr_fcv_asic_pe.h")
    inplace_change(filename,"jmexpr_scv_parser.h","priv_jmexpr_scv_parser.h")
    inplace_change(filename,"jmexpr_scv_tree.h","priv_jmexpr_scv_tree.h")
    inplace_change(filename,"jmexpr_scv_asic_pe.h","priv_jmexpr_scv_asic_pe.h")
    inplace_change(filename,"jmexpr_fcv.h","priv_jmexpr_fcv.h")
    inplace_change(filename,"jmexpr_beta_asic.h","priv_jmexpr_beta_asic.h")
    inplace_change(filename,"jmexpr_beta.h","priv_jmexpr_beta.h")
    inplace_change(filename,"jbeta_parser.h","priv_jbeta_parser.h")
    inplace_change(filename,"jbeta_tree.h","priv_jbeta_tree.h")
    inplace_change(filename,"jmexpr_beta_parser.h","priv_jmexpr_beta_parser.h")
    inplace_change(filename,"jmexpr_beta_tree.h","priv_jmexpr_beta_tree.h")
    inplace_change(filename,"jmexpr_beta_asic_pe.h","priv_jmexpr_beta_asic_pe.h")
    inplace_change(filename,"jbeta.h","priv_jbeta.h")
    inplace_change(filename,"jmexpr_dlu_alpha.h","priv_jmexpr_dlu_alpha.h")
    inplace_change(filename,"jmexpr_fw_action.h","priv_jmexpr_fw_action.h")
    inplace_change(filename,"jmexpr_fw_test.h","priv_jmexpr_fw_test.h")
    inplace_change(filename,"jmexpr_fw_sfm.h","priv_jmexpr_fw_sfm.h")
    inplace_change(filename,"jmexpr_fw_debug.h","priv_jmexpr_fw_debug.h")
    inplace_change(filename,"jmexpr_fw_parser.h","priv_jmexpr_fw_parser.h")
    inplace_change(filename,"jmexpr_fw_tree.h","priv_jmexpr_fw_tree.h")
    inplace_change(filename,"jmexpr_if.h","priv_jmexpr_if.h")
    inplace_change(filename,"zephyr_jif_api.h","priv_zephyr_jif_api.h")
    inplace_change(filename,"jmexpr_if_shared.h","priv_jmexpr_if_shared.h")
    inplace_change(filename,"jmexpr_sal_tree.h","priv_jmexpr_sal_tree.h")
    inplace_change(filename,"jmexpr_sal.h","priv_jmexpr_sal.h")
    inplace_change(filename,"jmexpr_sal_auaa.h","priv_jmexpr_sal_auaa.h")
    inplace_change(filename,"jmexpr_cpclass.h","priv_jmexpr_cpclass.h")
    inplace_change(filename,"jmexpr_mymac.h","priv_jmexpr_mymac.h")
    inplace_change(filename,"jmexpr_asic.h","priv_jmexpr_asic.h")
    inplace_change(filename,"jmexpr_utils_stubs.h","priv_jmexpr_utils_stubs.h")
    inplace_change(filename,"jmexpr_megidx_hash.h","priv_jmexpr_megidx_hash.h")
    inplace_change(filename,"hbtree.h","priv_hbtree.h")
    inplace_change(filename,"jmexpr_zephyr_hash.h","priv_jmexpr_zephyr_hash.h")
    inplace_change(filename,"zephyr_utils_api.h","priv_zephyr_utils_api.h")
    inplace_change(filename,"jmexpr_l3bnd.h","priv_jmexpr_l3bnd.h")
    inplace_change(filename,"jmexpr_lport_hash.h","priv_jmexpr_lport_hash.h")
    inplace_change(filename,"jmexpr_vpfe_platform.h","priv_jmexpr_vpfe_platform.h")
    inplace_change(filename,"jmexpr_etypes.h","priv_jmexpr_etypes.h")
    inplace_change(filename,"jmexpr_utils_tree.h","priv_jmexpr_utils_tree.h")
    inplace_change(filename,"jmexpr_hash.h","priv_jmexpr_hash.h")
    inplace_change(filename,"jmexpr_utils.h","priv_jmexpr_utils.h")
    inplace_change(filename,"jmexpr_sample_parser.h","priv_jmexpr_sample_parser.h")
    inplace_change(filename,"jmexpr_sample_tree.h","priv_jmexpr_sample_tree.h")
    inplace_change(filename,"jmexpr_sample.h","priv_jmexpr_sample.h")
    inplace_change(filename,"jmexpr_plct_tree.h","priv_jmexpr_plct_tree.h")
    inplace_change(filename,"jmexpr_tc_plct.h","priv_jmexpr_tc_plct.h")
    inplace_change(filename,"jmexpr_plct.h","priv_jmexpr_plct.h")
    inplace_change(filename,"jmexpr_plct_platform.h","priv_jmexpr_plct_platform.h")
    inplace_change(filename,"jmexpr_alpha.h","priv_jmexpr_alpha.h")
    inplace_change(filename,"address_hash.h","priv_address_hash.h")
    inplace_change(filename,"jmexpr_alpha_tree.h","priv_jmexpr_alpha_tree.h")
    inplace_change(filename,"poly_table.h","priv_poly_table.h")
    inplace_change(filename,"jmexpr_alpha_bft.h","priv_jmexpr_alpha_bft.h")
    inplace_change(filename,"jmexpr_nh_platform.h","priv_jmexpr_nh_platform.h")
    inplace_change(filename,"jmexpr_nh_parser.h","priv_jmexpr_nh_parser.h")
    inplace_change(filename,"jmexpr_nh_adaptive.h","priv_jmexpr_nh_adaptive.h")
    inplace_change(filename,"jmexpr_nh_ingress.h","priv_jmexpr_nh_ingress.h")
    inplace_change(filename,"jmexpr_nh_tree.h","priv_jmexpr_nh_tree.h")
    inplace_change(filename,"jmexpr_nh_export.h","priv_jmexpr_nh_export.h")
    inplace_change(filename,"zephyr_encap_const_mem.h","priv_zephyr_encap_const_mem.h")

def walk_dir():
    l = os.listdir(os.getcwd())
    for i in l:
        if os.path.isdir(i) == True:
            print (i)
            #replace_file(i)

#walk_dir()

#for root, directories, filenames in os.walk('/b/cmishra/PVT_ZH_BRINGUP_JUNOS_BRANCH/src/pfe/common/pfe-arch/mexpr/'):
for root, directories, filenames in os.walk(os.getcwd()):
    for filename in filenames: 
        print (filename)
        #print os.path.join(root,filename)
        replace_file(os.path.join(root,filename))
